// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvemsbqpzbthphwjalcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2ZW1zYnFwemJ0aHBod2phbGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDA5ODUsImV4cCI6MjA2NzMxNjk4NX0.9fSdBd-aD-A6VO3UZQpaYq5gAhADDKFEWMZEBBNF5Ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});